title: "Andrei made portofolio"
description: "Welcome to my personal portfolio page. Here you'll find my projects and contact information."
theme: jekyll-theme-cayman  # Optional, if you want to use a Jekyll theme like Cayman
